// ── Map data: domains, cross-domain edges, demo mastery seed ────────────────
// Edit this file to add/remove/modify nodes and connections.
// Each node: { id, label, r (radius from domain center), a (angle°), d (depth 1-6), msc, desc }
// Each domain: { id, label, cx, cy, rx, ry, col, nodes[], edges[] }

const domains=[

{id:"foundations_domain", label:"Foundations\n& Logic", cx:0, cy:0, rx:290, ry:260, col:"#5F5E5A",
 nodes:[
  {id:"informal_logic",label:"Informal Logic",      r:0,   a:0,   d:2, msc:"03A05", desc:"Logical connectives, quantifiers, basic proof techniques, mathematical writing."},
  {id:"set_theory",  label:"Set Theory",            r:55,  a:230, d:3, msc:"03E99", desc:"ZFC axioms, ordinals, cardinals, the continuum hypothesis, axiom of choice."},
  {id:"prop_logic",  label:"Propositional Logic",   r:52,  a:300, d:3, msc:"03B05", desc:"Syntax, semantics, truth tables, completeness, resolution."},
  {id:"pred_logic",  label:"First-Order Logic",     r:70,  a:340, d:3, msc:"03C99", desc:"First-order structures, satisfiability, completeness theorem (Gödel), compactness."},
  {id:"proof_theory",label:"Proof Theory",          r:95,  a:30,  d:4, msc:"03F99", desc:"Formal deduction, cut elimination, ordinal analysis, proof complexity."},
  {id:"model_theory",label:"Model Theory",          r:98,  a:340, d:4, msc:"03C99", desc:"Structures, elementary equivalence, types, compactness, ultraproducts."},
  {id:"computability",label:"Computability Theory", r:95,  a:270, d:4, msc:"03D99", desc:"Turing machines, halting problem, degrees of unsolvability, recursion theory."},
  {id:"set_adv",     label:"Set Theory (Advanced)", r:118, a:220, d:5, msc:"03E35", desc:"Forcing, large cardinals, inner model theory, determinacy."},
  {id:"type_theory", label:"Type Theory",           r:115, a:300, d:4, msc:"03B15", desc:"Simple type theory, dependent types, propositions as types (Curry-Howard)."},
  {id:"categ_found", label:"Categorical Foundations",r:128,a:120, d:5, msc:"18A15", desc:"Toposes as foundations, elementary theory of the category of sets (ETCS)."},
  {id:"reverse_math",label:"Reverse Mathematics",  r:130, a:40,  d:5, msc:"03B30", desc:"Which set-existence axioms are needed to prove theorems? Big Five subsystems."},
  {id:"homotopy_type",label:"Homotopy Type Theory",r:148, a:340, d:5, msc:"03B15", desc:"Univalence axiom, higher inductive types, identity types as paths."},
  {id:"descriptive_st",label:"Descriptive Set Theory",r:142,a:260,d:5,msc:"03E15",desc:"Borel, analytic, projective sets; perfect set property; determinacy consequences."},
  {id:"constructive",label:"Constructive Mathematics",r:130,a:80,d:4,msc:"03F65",desc:"Intuitionistic logic, Bishop-style constructivism, existence as computability."},
  {id:"large_cardinals",label:"Large Cardinals",   r:162, a:220, d:6, msc:"03E55", desc:"Inaccessible, Mahlo, measurable, supercompact. The hierarchy above ZFC."},
  {id:"abs_elem_theory",label:"Geometric Logic",   r:168, a:110, d:6, msc:"03G30", desc:"Geometric morphisms, classifying toposes, coherent theories."},
 ],
 edges:[
  {s:"informal_logic",t:"set_theory"},{s:"informal_logic",t:"prop_logic"},
  {s:"prop_logic",t:"pred_logic"},{s:"pred_logic",t:"model_theory"},
  {s:"pred_logic",t:"proof_theory"},{s:"set_theory",t:"set_adv"},
  {s:"pred_logic",t:"computability"},{s:"proof_theory",t:"reverse_math"},
  {s:"model_theory",t:"categ_found"},{s:"informal_logic",t:"type_theory"},
  {s:"type_theory",t:"homotopy_type"},{s:"set_theory",t:"descriptive_st"},
  {s:"set_adv",t:"large_cardinals"},{s:"categ_found",t:"abs_elem_theory"},
  {s:"type_theory",t:"constructive"},{s:"constructive",t:"homotopy_type"},
 ]
},

{id:"arith_domain", label:"Arithmetic &\nNumber Sense", cx:-460, cy:0, rx:195, ry:170, col:"#854F0B",
 nodes:[
  {id:"counting",    label:"Counting",              r:0,   a:0,   d:1, msc:"97A20", desc:"Natural numbers, one-to-one correspondence, cardinality of small sets."},
  {id:"arith_ops",   label:"Four Operations",       r:45,  a:200, d:1, msc:"97F30", desc:"Addition, subtraction, multiplication, division of whole numbers."},
  {id:"fractions",   label:"Fractions",             r:55,  a:280, d:1, msc:"97F40", desc:"Parts of a whole, equivalent fractions, addition and subtraction."},
  {id:"decimals",    label:"Decimals & Percents",   r:65,  a:340, d:1, msc:"97F40", desc:"Decimal notation, place value, percentage and proportion."},
  {id:"neg_nums",    label:"Negative Numbers",      r:58,  a:120, d:1, msc:"97F30", desc:"Integers, number line, signed arithmetic."},
  {id:"divisibility",label:"Divisibility",          r:80,  a:240, d:2, msc:"11A05", desc:"Factors, multiples, GCD, LCM, prime factorization."},
  {id:"primes_elem", label:"Prime Numbers",         r:92,  a:300, d:2, msc:"11A41", desc:"Sieve of Eratosthenes, infinitude of primes, fundamental theorem of arithmetic."},
  {id:"modular_arith",label:"Modular Arithmetic",  r:105, a:260, d:2, msc:"11A07", desc:"Congruences mod n, clock arithmetic, divisibility rules."},
  {id:"ratio_prop",  label:"Ratios & Proportions",  r:72,  a:160, d:2, msc:"97F50", desc:"Equivalent ratios, scaling, unit rates, direct and inverse proportion."},
  {id:"elem_combin", label:"Counting Principles",   r:115, a:200, d:3, msc:"05A05", desc:"Multiplication principle, permutations, combinations, Pascal's triangle."},
  {id:"num_systems", label:"Number Systems",        r:125, a:310, d:3, msc:"11A63", desc:"Binary, hexadecimal, other bases. Place value abstracted."},
  {id:"p_adic_elem", label:"p-adic Numbers",        r:160, a:280, d:5, msc:"11S80", desc:"p-adic absolute value, p-adic integers and rationals. A different completion of ℚ."},
  {id:"surreal",     label:"Surreal Numbers",       r:168, a:240, d:6, msc:"11R04", desc:"Conway's surreal numbers: a proper class extending reals and ordinals."},
 ],
 edges:[
  {s:"counting",t:"arith_ops"},{s:"arith_ops",t:"fractions"},{s:"arith_ops",t:"neg_nums"},
  {s:"fractions",t:"decimals"},{s:"arith_ops",t:"divisibility"},{s:"divisibility",t:"primes_elem"},
  {s:"divisibility",t:"modular_arith"},{s:"fractions",t:"ratio_prop"},
  {s:"primes_elem",t:"elem_combin"},{s:"modular_arith",t:"num_systems"},
  {s:"modular_arith",t:"p_adic_elem"},{s:"p_adic_elem",t:"surreal"},
 ]
},

{id:"algebra_domain", label:"Algebra", cx:-325, cy:-325, rx:225, ry:195, col:"#534AB7",
 nodes:[
  {id:"pre_alg",     label:"Pre-Algebra",           r:0,   a:0,   d:2, msc:"97H20", desc:"Variables and expressions. Translating word problems into equations."},
  {id:"alg1",        label:"Elementary Algebra",    r:50,  a:230, d:2, msc:"97H30", desc:"Linear equations and inequalities, graphing lines, systems of equations.",
   type:'course',
   topics:[
    {id:"alg1_vars",        label:"Variables &\nExpressions",   r:20, a:90,  d:2, msc:"97H20", desc:"Variables, constants, algebraic expressions. Translating English phrases to algebra."},
    {id:"alg1_solve_lin",   label:"Linear\nEquations",          r:20, a:45,  d:2, msc:"97H30", desc:"Solving one- and two-step linear equations in one variable using properties of equality."},
    {id:"alg1_solve_ineq",  label:"Inequalities",               r:20, a:0,   d:2, msc:"97H30", desc:"Solving and graphing linear inequalities on the number line; interval notation."},
    {id:"alg1_graph_lines", label:"Graphing\nLines",            r:20, a:315, d:2, msc:"97H30", desc:"Slope, intercepts, graphing linear equations in two variables; slope-intercept form."},
    {id:"alg1_systems",     label:"Systems of\nEquations",      r:20, a:270, d:2, msc:"97H30", desc:"Solving systems of two linear equations by substitution and elimination."},
    {id:"alg1_polynomials", label:"Polynomials",                r:20, a:225, d:2, msc:"97H40", desc:"Adding, subtracting, multiplying polynomials; laws of exponents."},
    {id:"alg1_factor",      label:"Factoring",                  r:20, a:180, d:2, msc:"97H40", desc:"Factoring GCF, trinomials, and difference of squares."},
    {id:"alg1_radicals",    label:"Radicals &\nRoots",          r:20, a:135, d:2, msc:"97H40", desc:"Square roots, cube roots, simplifying radicals, and rational exponents."},
   ],
   topicEdges:[
    {s:"alg1_vars",       t:"alg1_solve_lin"},
    {s:"alg1_vars",       t:"alg1_solve_ineq"},
    {s:"alg1_solve_lin",  t:"alg1_graph_lines"},
    {s:"alg1_solve_lin",  t:"alg1_systems"},
    {s:"alg1_graph_lines",t:"alg1_systems"},
    {s:"alg1_solve_lin",  t:"alg1_polynomials"},
    {s:"alg1_polynomials",t:"alg1_factor"},
    {s:"alg1_factor",     t:"alg1_radicals"},
   ]
  },
  {id:"alg2",        label:"Algebra II",            r:75,  a:290, d:2, msc:"97H40", desc:"Polynomials, quadratics, exponentials, logarithms, conic sections."},
  {id:"lin_alg_elem",label:"Linear Algebra",        r:90,  a:340, d:3, msc:"15A03", desc:"Vectors, matrices, determinants, linear transformations, eigenvalues."},
  {id:"intro_proofs_alg",label:"Intro to Proofs",   r:80,  a:150, d:3, msc:"97E50", desc:"Direct proof, contradiction, induction. First exposure to rigorous mathematics."},
  {id:"group_theory",label:"Group Theory",          r:120, a:50,  d:4, msc:"20-01", desc:"Groups, subgroups, homomorphisms, quotient groups, group actions."},
  {id:"ring_theory", label:"Ring Theory",           r:125, a:100, d:4, msc:"13-01", desc:"Rings, ideals, quotient rings, integral domains, PIDs, UFDs."},
  {id:"field_theory",label:"Field Theory",          r:120, a:310, d:4, msc:"12F05", desc:"Field extensions, algebraic and transcendental elements, splitting fields."},
  {id:"galois",      label:"Galois Theory",         r:148, a:340, d:4, msc:"12F10", desc:"Galois correspondence, solvability by radicals, fundamental theorem."},
  {id:"modules",     label:"Module Theory",         r:140, a:130, d:4, msc:"16D10", desc:"Modules over rings, free and projective modules, exact sequences."},
  {id:"multilinear", label:"Multilinear Algebra",   r:110, a:270, d:4, msc:"15A69", desc:"Tensor products, exterior algebra, symmetric algebra."},
  {id:"comm_alg",    label:"Commutative Algebra",   r:162, a:80,  d:5, msc:"13A99", desc:"Noetherian rings, localization, Spec, dimension theory, completions."},
  {id:"homol_alg",   label:"Homological Algebra",   r:168, a:120, d:5, msc:"18G99", desc:"Chain complexes, derived functors, Ext and Tor, spectral sequences."},
  {id:"lie_alg",     label:"Lie Algebras",          r:170, a:30,  d:5, msc:"17B05", desc:"Lie brackets, solvable and semisimple Lie algebras, root systems, classification."},
  {id:"repr_theory", label:"Representation Theory", r:178, a:60,  d:5, msc:"20C99", desc:"Group representations, characters, Schur's lemma, induced representations."},
  {id:"cat_theory",  label:"Category Theory",       r:155, a:200, d:5, msc:"18A99", desc:"Categories, functors, natural transformations, limits, adjoints, Yoneda lemma."},
  {id:"k_theory_alg",label:"Algebraic K-Theory",   r:192, a:150, d:6, msc:"19-99", desc:"K₀, K₁, higher K-groups, Quillen's Q-construction."},
  {id:"infty_cats",  label:"∞-Categories",          r:200, a:185, d:6, msc:"18N60", desc:"Quasicategories, model categories, higher topos theory."},
  {id:"derived_alg", label:"Derived Algebraic Geometry",r:205,a:100,d:6,msc:"14A30",desc:"Derived stacks, structured ring spectra. The algebro-geometric frontier."},
 ],
 edges:[
  {s:"pre_alg",t:"alg1"},{s:"alg1",t:"alg2"},{s:"alg2",t:"lin_alg_elem"},
  {s:"alg1",t:"intro_proofs_alg"},{s:"intro_proofs_alg",t:"group_theory"},
  {s:"intro_proofs_alg",t:"ring_theory"},{s:"lin_alg_elem",t:"group_theory"},
  {s:"alg2",t:"field_theory"},{s:"ring_theory",t:"field_theory"},
  {s:"field_theory",t:"galois"},{s:"ring_theory",t:"modules"},
  {s:"lin_alg_elem",t:"multilinear"},{s:"modules",t:"multilinear"},
  {s:"ring_theory",t:"comm_alg"},{s:"modules",t:"homol_alg"},
  {s:"comm_alg",t:"homol_alg"},{s:"group_theory",t:"lie_alg"},
  {s:"group_theory",t:"repr_theory"},{s:"intro_proofs_alg",t:"cat_theory"},
  {s:"homol_alg",t:"k_theory_alg"},{s:"cat_theory",t:"infty_cats"},
  {s:"homol_alg",t:"derived_alg"},{s:"comm_alg",t:"derived_alg"},
 ]
},

{id:"analysis_domain", label:"Analysis", cx:0, cy:-460, rx:235, ry:200, col:"#185FA5",
 nodes:[
  {id:"precalc",     label:"Pre-Calculus",          r:0,   a:0,   d:2, msc:"97I20", desc:"Functions, transformations, conic sections, introduction to limits intuitively."},
  {id:"calc1",       label:"Calculus I",            r:52,  a:250, d:3, msc:"26A06", desc:"Limits, continuity, derivatives, differentiation rules, applications."},
  {id:"calc2",       label:"Calculus II",           r:80,  a:300, d:3, msc:"26A06", desc:"Integration, fundamental theorem of calculus, techniques, series."},
  {id:"multi_calc",  label:"Multivariable Calculus",r:100, a:340, d:3, msc:"26B12", desc:"Partial derivatives, gradient, multiple integrals, vector calculus, Stokes' theorem."},
  {id:"ode",         label:"ODEs",                  r:95,  a:210, d:3, msc:"34A30", desc:"First and second order equations, systems, phase plane, Laplace transforms."},
  {id:"real_anal",   label:"Real Analysis",         r:128, a:270, d:4, msc:"26-01", desc:"Rigorous limits, continuity, differentiation, Riemann integration, metric spaces."},
  {id:"complex_anal",label:"Complex Analysis",      r:132, a:330, d:4, msc:"30-01", desc:"Holomorphic functions, Cauchy's theorem, Laurent series, residues, conformal maps."},
  {id:"sequences_series",label:"Sequences & Series",r:112, a:180, d:3, msc:"40-01", desc:"Convergence tests, power series, Taylor series, uniform convergence."},
  {id:"vector_calc", label:"Vector Analysis",       r:108, a:10,  d:3, msc:"26B20", desc:"Divergence theorem, Green's theorem, differential forms in ℝⁿ."},
  {id:"pde",         label:"PDEs",                  r:148, a:230, d:4, msc:"35-01", desc:"Heat equation, wave equation, Laplace equation, separation of variables, Fourier methods."},
  {id:"measure",     label:"Measure Theory",        r:155, a:280, d:5, msc:"28A99", desc:"σ-algebras, Lebesgue measure, integration, convergence theorems, product measures."},
  {id:"func_anal",   label:"Functional Analysis",   r:158, a:330, d:5, msc:"46-01", desc:"Banach and Hilbert spaces, bounded operators, Hahn-Banach, open mapping, spectral theory."},
  {id:"fourier",     label:"Fourier Analysis",      r:148, a:170, d:4, msc:"42A99", desc:"Fourier series, Fourier transform, convolution, uncertainty principle."},
  {id:"approx_theory",label:"Approximation Theory",r:140, a:130, d:4, msc:"41A99", desc:"Best approximation, Weierstrass theorem, Chebyshev polynomials, splines."},
  {id:"special_funcs",label:"Special Functions",    r:135, a:80,  d:4, msc:"33-01", desc:"Gamma function, Bessel functions, orthogonal polynomials, hypergeometric series."},
  {id:"harm_anal",   label:"Harmonic Analysis",     r:175, a:200, d:5, msc:"43A99", desc:"Abstract harmonic analysis on groups, wavelet theory, singular integrals."},
  {id:"complex_several",label:"Several Complex Variables",r:172,a:350,d:5,msc:"32A99",desc:"Holomorphic functions in ℂⁿ, domains of holomorphy, Cousin problems, Stein manifolds."},
  {id:"operator_theory",label:"Operator Theory",    r:178, a:310, d:5, msc:"47-01", desc:"Spectral theory, C*-algebras, von Neumann algebras, unbounded operators."},
  {id:"calculus_variations",label:"Calculus of Variations",r:165,a:140,d:5,msc:"49-01",desc:"Euler-Lagrange equations, brachistochrone, minimal surfaces, optimal control."},
  {id:"nonlinear_anal",label:"Nonlinear Analysis",  r:190, a:250, d:5, msc:"47H99", desc:"Fixed point theorems, degree theory, bifurcation, variational methods."},
  {id:"microlocal",  label:"Microlocal Analysis",   r:200, a:290, d:6, msc:"35S99", desc:"Pseudodifferential operators, wavefront sets, propagation of singularities."},
  {id:"free_boundary",label:"Free Boundary Problems",r:205,a:230,d:6,msc:"35R35",desc:"Obstacle problem, Stefan problem, regularity of free boundaries."},
 ],
 edges:[
  {s:"precalc",t:"calc1"},{s:"calc1",t:"calc2"},{s:"calc2",t:"multi_calc"},
  {s:"calc2",t:"ode"},{s:"calc2",t:"sequences_series"},{s:"multi_calc",t:"vector_calc"},
  {s:"calc2",t:"real_anal"},{s:"real_anal",t:"complex_anal"},
  {s:"real_anal",t:"measure"},{s:"sequences_series",t:"fourier"},
  {s:"ode",t:"pde"},{s:"real_anal",t:"pde"},{s:"measure",t:"func_anal"},
  {s:"fourier",t:"harm_anal"},{s:"func_anal",t:"harm_anal"},
  {s:"complex_anal",t:"complex_several"},{s:"func_anal",t:"operator_theory"},
  {s:"multi_calc",t:"calculus_variations"},{s:"func_anal",t:"nonlinear_anal"},
  {s:"pde",t:"microlocal"},{s:"pde",t:"free_boundary"},
  {s:"calc2",t:"approx_theory"},{s:"calc2",t:"special_funcs"},
 ]
},

{id:"geom_domain", label:"Geometry &\nTopology", cx:325, cy:-325, rx:220, ry:190, col:"#0F6E56",
 nodes:[
  {id:"eucl_geom",   label:"Euclidean Geometry",    r:0,   a:0,   d:1, msc:"51M05", desc:"Points, lines, triangles, circles. Euclidean axioms and classical theorems."},
  {id:"trig",        label:"Trigonometry",          r:55,  a:280, d:2, msc:"51N20", desc:"Sine, cosine, tangent, unit circle, identities, law of sines and cosines."},
  {id:"coord_geom",  label:"Coordinate Geometry",   r:60,  a:330, d:2, msc:"51N10", desc:"Cartesian plane, equations of lines and conics, distance formula."},
  {id:"solid_geom",  label:"Solid Geometry",        r:60,  a:200, d:2, msc:"51M20", desc:"3D shapes, volumes, surface areas, cross-sections."},
  {id:"projective",  label:"Projective Geometry",   r:100, a:30,  d:3, msc:"51A05", desc:"Points at infinity, duality, cross-ratio, projective transformations."},
  {id:"affine_geom", label:"Affine Geometry",       r:95,  a:350, d:3, msc:"51N10", desc:"Affine transformations, parallelism, affine independence."},
  {id:"convex_geom", label:"Convex Geometry",       r:100, a:230, d:3, msc:"52A99", desc:"Convex sets, supporting hyperplanes, Helly's theorem, polytopes."},
  {id:"gen_topology",label:"General Topology",      r:120, a:80,  d:4, msc:"54-01", desc:"Open/closed sets, compactness, connectedness, continuity, separation axioms."},
  {id:"diff_geom",   label:"Differential Geometry", r:130, a:340, d:4, msc:"53-01", desc:"Curves, surfaces, curvature, geodesics, Gauss-Bonnet theorem."},
  {id:"alg_top",     label:"Algebraic Topology",    r:148, a:60,  d:4, msc:"55-01", desc:"Fundamental group, covering spaces, homology, cohomology, CW complexes."},
  {id:"disc_geom",   label:"Discrete Geometry",     r:115, a:170, d:4, msc:"52C99", desc:"Lattices, sphere packing, tilings, combinatorial geometry."},
  {id:"riemann_geom",label:"Riemannian Geometry",   r:165, a:10,  d:5, msc:"53B20", desc:"Riemannian manifolds, connection, curvature tensor, geodesic completeness."},
  {id:"lie_groups",  label:"Lie Groups",            r:162, a:340, d:5, msc:"22E99", desc:"Smooth manifolds with group structure, exponential map, adjoint representation."},
  {id:"alg_geom_basic",label:"Algebraic Geometry",  r:168, a:90,  d:5, msc:"14-01", desc:"Varieties, schemes, sheaves, morphisms, Zariski topology."},
  {id:"knot_theory", label:"Knot Theory",           r:155, a:130, d:4, msc:"57M25", desc:"Knot invariants, Jones polynomial, knot groups, surgery on knots."},
  {id:"manifolds",   label:"Manifold Theory",       r:152, a:50,  d:5, msc:"57-01", desc:"Smooth manifolds, tangent bundles, vector bundles, transversality."},
  {id:"symplectic",  label:"Symplectic Geometry",   r:175, a:310, d:5, msc:"53D99", desc:"Symplectic manifolds, Hamiltonian systems, Lagrangian submanifolds."},
  {id:"complex_geom",label:"Complex Geometry",      r:180, a:360, d:5, msc:"53C55", desc:"Kähler manifolds, Hodge theory, line bundles, complex structures."},
  {id:"homotopy_theory",label:"Homotopy Theory",    r:185, a:75,  d:5, msc:"55P99", desc:"Homotopy groups, fibrations, Hurewicz theorem, Whitehead theorem, spectra."},
  {id:"four_manifolds",label:"4-Manifold Theory",   r:198, a:40,  d:6, msc:"57K40", desc:"Donaldson theory, Seiberg-Witten invariants, exotic ℝ⁴."},
  {id:"geometric_group_theory",label:"Geometric Group Theory",r:195,a:120,d:6,msc:"20F65",desc:"Cayley graphs, word metrics, hyperbolic groups, quasi-isometries."},
  {id:"derived_cats_geom",label:"Derived Categories",r:202,a:95,d:6,msc:"14F08",desc:"Derived category of coherent sheaves, Fourier-Mukai transforms, mirror symmetry."},
 ],
 edges:[
  {s:"eucl_geom",t:"trig"},{s:"eucl_geom",t:"coord_geom"},{s:"eucl_geom",t:"solid_geom"},
  {s:"coord_geom",t:"projective"},{s:"coord_geom",t:"affine_geom"},
  {s:"eucl_geom",t:"convex_geom"},{s:"trig",t:"diff_geom"},
  {s:"affine_geom",t:"gen_topology"},{s:"projective",t:"gen_topology"},
  {s:"gen_topology",t:"alg_top"},{s:"gen_topology",t:"diff_geom"},
  {s:"diff_geom",t:"riemann_geom"},{s:"diff_geom",t:"lie_groups"},
  {s:"alg_top",t:"alg_geom_basic"},{s:"alg_top",t:"knot_theory"},
  {s:"diff_geom",t:"manifolds"},{s:"manifolds",t:"symplectic"},
  {s:"diff_geom",t:"complex_geom"},{s:"alg_top",t:"homotopy_theory"},
  {s:"manifolds",t:"four_manifolds"},{s:"alg_top",t:"geometric_group_theory"},
  {s:"alg_geom_basic",t:"derived_cats_geom"},{s:"convex_geom",t:"disc_geom"},
 ]
},

{id:"numthry_domain", label:"Number Theory", cx:460, cy:0, rx:210, ry:185, col:"#BA7517",
 nodes:[
  {id:"elem_num",    label:"Elementary Number Theory",r:0,  a:0,   d:3, msc:"11A99", desc:"Divisibility, GCD, primes, congruences, Chinese Remainder Theorem."},
  {id:"quad_res",    label:"Quadratic Residues",     r:65,  a:330, d:3, msc:"11A15", desc:"Legendre symbol, quadratic reciprocity, Euler's criterion."},
  {id:"arith_funcs", label:"Arithmetic Functions",   r:65,  a:60,  d:3, msc:"11A25", desc:"Euler's totient, Möbius function, multiplicative functions, Dirichlet series."},
  {id:"dioph_basic", label:"Diophantine Equations",  r:75,  a:160, d:3, msc:"11D99", desc:"Integer solutions: linear, Pythagorean triples, Pell's equation."},
  {id:"cont_fracs",  label:"Continued Fractions",    r:80,  a:240, d:3, msc:"11A55", desc:"Simple continued fractions, convergents, approximation of irrationals."},
  {id:"analytic_nt", label:"Analytic Number Theory", r:110, a:30,  d:4, msc:"11M99", desc:"Riemann zeta function, prime number theorem, Dirichlet's theorem on primes."},
  {id:"alg_nt",      label:"Algebraic Number Theory",r:115, a:340, d:4, msc:"11R99", desc:"Number fields, rings of integers, ideals, class group, unit theorem."},
  {id:"elliptic",    label:"Elliptic Curves",        r:118, a:110, d:4, msc:"11G05", desc:"Weierstrass form, group law, rational points, torsion, rank."},
  {id:"local_fields",label:"Local Fields",           r:130, a:290, d:5, msc:"11S99", desc:"p-adic fields, completions, local-global principles (Hasse-Minkowski)."},
  {id:"class_field", label:"Class Field Theory",     r:148, a:350, d:5, msc:"11R37", desc:"Abelian extensions, Artin map, reciprocity laws, idèles."},
  {id:"modular_forms",label:"Modular Forms",         r:145, a:50,  d:5, msc:"11F11", desc:"Holomorphic modular forms, Hecke operators, L-functions, modularity."},
  {id:"arith_geom",  label:"Arithmetic Geometry",    r:162, a:130, d:5, msc:"11G99", desc:"Rational points on varieties, heights, Faltings' theorem."},
  {id:"iwasawa",     label:"Iwasawa Theory",         r:175, a:310, d:6, msc:"11R23", desc:"Zp-extensions, Iwasawa algebra, Main Conjecture."},
  {id:"langlands",   label:"Langlands Program",      r:185, a:30,  d:6, msc:"11R39", desc:"Functoriality, automorphic representations, reciprocity conjectures."},
  {id:"abc_conjecture",label:"abc Conjecture",       r:192, a:80,  d:6, msc:"11D45", desc:"The abc conjecture, Szpiro's conjecture, inter-universal Teichmüller theory."},
  {id:"additive_nt", label:"Additive Number Theory",r:100, a:200, d:4, msc:"11P99", desc:"Goldbach conjecture, Waring's problem, sums of squares, circle method."},
 ],
 edges:[
  {s:"elem_num",t:"quad_res"},{s:"elem_num",t:"arith_funcs"},{s:"elem_num",t:"dioph_basic"},
  {s:"elem_num",t:"cont_fracs"},{s:"arith_funcs",t:"analytic_nt"},
  {s:"quad_res",t:"alg_nt"},{s:"analytic_nt",t:"modular_forms"},
  {s:"alg_nt",t:"class_field"},{s:"alg_nt",t:"local_fields"},
  {s:"dioph_basic",t:"elliptic"},{s:"elliptic",t:"arith_geom"},
  {s:"class_field",t:"langlands"},{s:"modular_forms",t:"langlands"},
  {s:"arith_geom",t:"langlands"},{s:"local_fields",t:"iwasawa"},
  {s:"iwasawa",t:"langlands"},{s:"elem_num",t:"additive_nt"},
  {s:"elliptic",t:"abc_conjecture"},
 ]
},

{id:"discrete_domain", label:"Discrete Math &\nCombinatorics", cx:325, cy:325, rx:215, ry:185, col:"#993C1D",
 nodes:[
  {id:"logic_basic", label:"Logic & Proof",         r:0,   a:0,   d:2, msc:"03B05", desc:"Propositional logic, truth tables, basic proof strategies."},
  {id:"sets_funcs",  label:"Sets & Functions",       r:50,  a:220, d:2, msc:"03E99", desc:"Set operations, Venn diagrams, functions, injections and surjections."},
  {id:"graph_basic", label:"Graph Theory",           r:68,  a:310, d:3, msc:"05C99", desc:"Graphs, paths, cycles, trees, planarity, coloring, matchings."},
  {id:"enum_combin", label:"Enumerative Combinatorics",r:72, a:50,  d:3, msc:"05A99", desc:"Binomial coefficients, inclusion-exclusion, generating functions, recurrences."},
  {id:"relations",   label:"Relations & Order",      r:62,  a:160, d:2, msc:"06A99", desc:"Equivalence relations, partial orders, lattices, Hasse diagrams."},
  {id:"alg_combin",  label:"Algebraic Combinatorics",r:110, a:30,  d:4, msc:"05E99", desc:"Symmetric functions, Young tableaux, RSK correspondence, q-analogs."},
  {id:"extremal",    label:"Extremal Combinatorics", r:112, a:80,  d:4, msc:"05D99", desc:"Turán's theorem, Ramsey theory, Szemerédi regularity lemma."},
  {id:"prob_combin", label:"Probabilistic Method",   r:115, a:330, d:4, msc:"05C80", desc:"Erdős's probabilistic method, random graphs, threshold phenomena."},
  {id:"lattice_order",label:"Lattice Theory",        r:105, a:180, d:4, msc:"06B99", desc:"Distributive and modular lattices, Boolean algebras, Stone duality."},
  {id:"coding_theory",label:"Coding Theory",         r:125, a:270, d:4, msc:"94B99", desc:"Error-correcting codes, Hamming codes, Reed-Solomon, linear codes."},
  {id:"comb_geom",   label:"Combinatorial Geometry", r:120, a:130, d:4, msc:"52C10", desc:"Arrangements of hyperplanes, point-line incidences, Szemerédi-Trotter."},
  {id:"matroid",     label:"Matroid Theory",         r:138, a:60,  d:5, msc:"05B35", desc:"Matroids, circuits, duality, representability, Tutte polynomial."},
  {id:"topological_combin",label:"Topological Combinatorics",r:145,a:340,d:5,msc:"05E45",desc:"Discrete Morse theory, shellability, combinatorics of simplicial complexes."},
  {id:"inf_combin",  label:"Infinite Combinatorics", r:152, a:200, d:5, msc:"03E05", desc:"Ramsey theory for infinite sets, partition calculus, cardinal arithmetic."},
  {id:"chromatic_homotopy",label:"Chromatic Combinatorics",r:162,a:100,d:6,msc:"05C15",desc:"Graph homomorphisms, Hedetniemi conjecture, category-theoretic coloring."},
 ],
 edges:[
  {s:"logic_basic",t:"sets_funcs"},{s:"sets_funcs",t:"graph_basic"},
  {s:"sets_funcs",t:"enum_combin"},{s:"sets_funcs",t:"relations"},
  {s:"enum_combin",t:"alg_combin"},{s:"graph_basic",t:"extremal"},
  {s:"graph_basic",t:"prob_combin"},{s:"relations",t:"lattice_order"},
  {s:"enum_combin",t:"coding_theory"},{s:"graph_basic",t:"comb_geom"},
  {s:"alg_combin",t:"matroid"},{s:"graph_basic",t:"topological_combin"},
  {s:"lattice_order",t:"inf_combin"},{s:"matroid",t:"chromatic_homotopy"},
 ]
},

{id:"prob_domain", label:"Probability &\nStatistics", cx:0, cy:460, rx:210, ry:182, col:"#3B6D11",
 nodes:[
  {id:"basic_prob",  label:"Basic Probability",      r:0,   a:0,   d:2, msc:"97K50", desc:"Sample spaces, events, probability axioms, conditional probability, Bayes' theorem."},
  {id:"basic_stats", label:"Descriptive Statistics", r:50,  a:210, d:2, msc:"62A01", desc:"Mean, median, mode, variance, standard deviation, histograms."},
  {id:"counting_prob",label:"Counting & Probability",r:58,  a:300, d:2, msc:"60C05", desc:"Permutations, combinations, geometric probability."},
  {id:"discrete_rv", label:"Discrete Distributions", r:72,  a:30,  d:3, msc:"60E05", desc:"Bernoulli, binomial, Poisson, geometric. Expectation and variance."},
  {id:"contin_rv",   label:"Continuous Distributions",r:78, a:330, d:3, msc:"60E15", desc:"Uniform, exponential, normal distribution. PDFs and CDFs."},
  {id:"inference",   label:"Statistical Inference",   r:88,  a:250, d:3, msc:"62F99", desc:"Hypothesis testing, confidence intervals, p-values, t-tests."},
  {id:"regression",  label:"Regression & GLMs",       r:95,  a:170, d:3, msc:"62J99", desc:"Linear regression, least squares, generalized linear models, logistic regression."},
  {id:"markov",      label:"Markov Chains",           r:105, a:60,  d:4, msc:"60J10", desc:"Transition matrices, stationary distributions, convergence, mixing times."},
  {id:"prob_theory", label:"Probability Theory",      r:115, a:310, d:4, msc:"60A99", desc:"Measure-theoretic probability, random variables, expectation, LLN, CLT."},
  {id:"stoch_proc",  label:"Stochastic Processes",    r:122, a:20,  d:4, msc:"60G99", desc:"Brownian motion, Poisson process, martingales, filtrations."},
  {id:"bayesian",    label:"Bayesian Statistics",     r:118, a:200, d:4, msc:"62F15", desc:"Prior and posterior distributions, MCMC, conjugate priors, hierarchical models."},
  {id:"multivar_stats",label:"Multivariate Statistics",r:112,a:130,d:4,msc:"62H99",desc:"Principal component analysis, factor analysis, MANOVA, covariance structure."},
  {id:"stoch_calc",  label:"Stochastic Calculus",     r:148, a:350, d:5, msc:"60H99", desc:"Itô integral, Itô's lemma, stochastic differential equations, Girsanov's theorem."},
  {id:"large_deviations",label:"Large Deviations",   r:152, a:40,  d:5, msc:"60F10", desc:"Cramér's theorem, Sanov's theorem, free energy, rate functions."},
  {id:"random_matrices",label:"Random Matrices",     r:158, a:310, d:5, msc:"60B20", desc:"GUE, GOE, eigenvalue distribution, Tracy-Widom law, universality."},
  {id:"ergodic",     label:"Ergodic Theory",          r:148, a:270, d:5, msc:"37A99", desc:"Measure-preserving transformations, ergodicity, mixing, Birkhoff ergodic theorem."},
  {id:"statistical_learning",label:"Statistical Learning",r:140,a:160,d:4,msc:"62M45",desc:"Bias-variance tradeoff, cross-validation, regularization, model selection."},
  {id:"free_prob",   label:"Free Probability",        r:172, a:330, d:6, msc:"46L54", desc:"Free independence, free cumulants, connections to random matrices and operator algebras."},
  {id:"spde",        label:"SPDEs",                   r:175, a:10,  d:6, msc:"60H15", desc:"Stochastic partial differential equations, white noise analysis, invariant measures."},
 ],
 edges:[
  {s:"basic_prob",t:"basic_stats"},{s:"basic_prob",t:"counting_prob"},
  {s:"basic_prob",t:"discrete_rv"},{s:"basic_prob",t:"contin_rv"},
  {s:"basic_stats",t:"inference"},{s:"basic_stats",t:"regression"},
  {s:"discrete_rv",t:"markov"},{s:"contin_rv",t:"prob_theory"},
  {s:"prob_theory",t:"stoch_proc"},{s:"inference",t:"bayesian"},
  {s:"basic_stats",t:"multivar_stats"},{s:"stoch_proc",t:"stoch_calc"},
  {s:"prob_theory",t:"large_deviations"},{s:"prob_theory",t:"random_matrices"},
  {s:"stoch_proc",t:"ergodic"},{s:"regression",t:"statistical_learning"},
  {s:"random_matrices",t:"free_prob"},{s:"stoch_calc",t:"spde"},
 ]
},

{id:"applied_domain", label:"Applied &\nComputational Math", cx:-325, cy:325, rx:225, ry:195, col:"#993556",
 nodes:[
  {id:"applied_intro",label:"Mathematical Modeling",r:0,  a:0,   d:2, msc:"00A71", desc:"Translating real-world problems into mathematical form. Dimensional analysis, estimation."},
  {id:"numerical_basic",label:"Numerical Methods", r:58,  a:270, d:3, msc:"65-01", desc:"Root-finding, numerical integration, interpolation, floating-point arithmetic."},
  {id:"linear_prog", label:"Linear Programming",    r:62,  a:200, d:3, msc:"90C05", desc:"Simplex method, duality, sensitivity analysis, network flows."},
  {id:"dyn_systems_basic",label:"Dynamical Systems",r:70, a:320, d:3, msc:"37-01", desc:"Equilibria, stability, phase portraits, bifurcations, chaos in 1D and 2D."},
  {id:"odes_applied", label:"Applied ODEs",          r:65,  a:100, d:3, msc:"34B99", desc:"Modeling with ODEs, systems of equations, numerical methods, applications in science."},
  {id:"fourier_applied",label:"Applied Fourier Analysis",r:80,a:160,d:3,msc:"42-01",desc:"Signal processing, DFT, FFT algorithm, filtering, spectral analysis."},
  {id:"numerical_lin",label:"Numerical Linear Algebra",r:100,a:240,d:4,msc:"65F99",desc:"LU, QR, SVD decompositions, iterative solvers, condition numbers, stability."},
  {id:"optimization", label:"Optimization",          r:102, a:180, d:4, msc:"90C99", desc:"Convex optimization, gradient descent, Lagrange multipliers, KKT conditions."},
  {id:"pdes_applied", label:"Applied PDEs",          r:105, a:340, d:4, msc:"35-01", desc:"Heat, wave, Laplace equations. Finite difference and finite element methods."},
  {id:"control_theory",label:"Control Theory",       r:110, a:130, d:4, msc:"93-01", desc:"Feedback systems, Laplace transforms, stability (Routh, Nyquist), optimal control."},
  {id:"game_theory",  label:"Game Theory",           r:105, a:60,  d:4, msc:"91A99", desc:"Nash equilibria, zero-sum games, cooperative games, mechanism design."},
  {id:"info_theory",  label:"Information Theory",    r:115, a:290, d:4, msc:"94A17", desc:"Entropy, channel capacity, Shannon's theorem, data compression, error bounds."},
  {id:"math_biology", label:"Mathematical Biology",  r:120, a:20,  d:4, msc:"92B99", desc:"Population dynamics, epidemic modeling (SIR), pattern formation, reaction-diffusion."},
  {id:"fin_math",     label:"Mathematical Finance",  r:118, a:100, d:4, msc:"91G99", desc:"Black-Scholes, stochastic calculus in finance, risk-neutral pricing, derivatives."},
  {id:"geom_measure", label:"Geometric Measure Theory",r:145,a:310,d:5,msc:"49Q99",desc:"Rectifiable sets, currents, varifolds, minimal surfaces via GMT."},
  {id:"topological_data",label:"Topological Data Analysis",r:142,a:250,d:5,msc:"55N31",desc:"Persistent homology, Betti numbers, mapper algorithm, shape analysis of data."},
  {id:"compressed_sensing",label:"Compressed Sensing",r:148,a:200,d:5,msc:"94A12",desc:"Sparse recovery, RIP condition, basis pursuit, applications in imaging."},
  {id:"math_physics", label:"Mathematical Physics",  r:155, a:40,  d:5, msc:"81-01", desc:"Rigorous foundations: quantum mechanics operators, C*-algebras, scattering theory."},
  {id:"numerics_adv", label:"Numerical Analysis (Advanced)",r:158,a:340,d:5,msc:"65M99",desc:"Finite element analysis, multigrid methods, spectral methods, error analysis."},
  {id:"mean_field",   label:"Mean Field Theory",     r:172, a:140, d:6, msc:"82C99", desc:"Mean-field games, McKean-Vlasov equations, propagation of chaos."},
  {id:"optimal_transport",label:"Optimal Transport", r:168, a:270, d:5, msc:"49Q22", desc:"Wasserstein distance, Brenier's theorem, displacement convexity."},
 ],
 edges:[
  {s:"applied_intro",t:"numerical_basic"},{s:"applied_intro",t:"linear_prog"},
  {s:"applied_intro",t:"dyn_systems_basic"},{s:"applied_intro",t:"odes_applied"},
  {s:"applied_intro",t:"fourier_applied"},{s:"numerical_basic",t:"numerical_lin"},
  {s:"linear_prog",t:"optimization"},{s:"dyn_systems_basic",t:"pdes_applied"},
  {s:"odes_applied",t:"control_theory"},{s:"optimization",t:"compressed_sensing"},
  {s:"fourier_applied",t:"info_theory"},{s:"numerical_lin",t:"numerics_adv"},
  {s:"applied_intro",t:"game_theory"},{s:"applied_intro",t:"math_biology"},
  {s:"odes_applied",t:"fin_math"},{s:"pdes_applied",t:"geom_measure"},
  {s:"numerical_basic",t:"topological_data"},{s:"optimization",t:"optimal_transport"},
  {s:"math_biology",t:"mean_field"},{s:"info_theory",t:"compressed_sensing"},
  {s:"optimization",t:"math_physics"},
 ]
},

];

const crossEdges=[
  {s:"primes_elem",    t:"elem_num"},
  {s:"modular_arith",  t:"group_theory"},
  {s:"arith_ops",      t:"pre_alg"},
  {s:"elem_combin",    t:"enum_combin"},
  {s:"lin_alg_elem",   t:"multi_calc"},
  {s:"multilinear",    t:"diff_geom"},
  {s:"lin_alg_elem",   t:"func_anal"},
  {s:"group_theory",   t:"lie_groups"},
  {s:"comm_alg",       t:"alg_geom_basic"},
  {s:"ring_theory",    t:"alg_geom_basic"},
  {s:"cat_theory",     t:"alg_top"},
  {s:"homol_alg",      t:"alg_top"},
  {s:"repr_theory",    t:"lie_groups"},
  {s:"ring_theory",    t:"alg_nt"},
  {s:"field_theory",   t:"alg_nt"},
  {s:"galois",         t:"alg_nt"},
  {s:"lie_alg",        t:"langlands"},
  {s:"real_anal",      t:"gen_topology"},
  {s:"complex_anal",   t:"riemann_geom"},
  {s:"measure",        t:"ergodic"},
  {s:"func_anal",      t:"operator_theory"},
  {s:"complex_anal",   t:"analytic_nt"},
  {s:"fourier",        t:"analytic_nt"},
  {s:"func_anal",      t:"modular_forms"},
  {s:"ode",            t:"odes_applied"},
  {s:"pde",            t:"pdes_applied"},
  {s:"calculus_variations",t:"optimal_transport"},
  {s:"harm_anal",      t:"fourier_applied"},
  {s:"stoch_calc",     t:"fin_math"},
  {s:"alg_geom_basic", t:"arith_geom"},
  {s:"riemann_geom",   t:"arith_geom"},
  {s:"manifolds",      t:"langlands"},
  {s:"diff_geom",      t:"math_physics"},
  {s:"symplectic",     t:"math_physics"},
  {s:"graph_basic",    t:"linear_prog"},
  {s:"coding_theory",  t:"info_theory"},
  {s:"enum_combin",    t:"math_biology"},
  {s:"prob_theory",    t:"fin_math"},
  {s:"stoch_proc",     t:"control_theory"},
  {s:"statistical_learning",t:"compressed_sensing"},
  {s:"set_theory",     t:"cat_theory"},
  {s:"type_theory",    t:"cat_theory"},
  {s:"pred_logic",     t:"model_theory"},
  {s:"set_theory",     t:"measure"},
  {s:"set_adv",        t:"descriptive_st"},
  {s:"prob_theory",    t:"measure"},
  {s:"ergodic",        t:"harm_anal"},
  {s:"analytic_nt",    t:"complex_anal"},
  {s:"lin_alg_elem",   t:"numerical_lin"},
  {s:"cat_theory",     t:"info_theory"},
];

// Demo mastery seed — pre-filled values for visual testing.
// Remove this (and the Object.entries call in map-engine.js) when real persistence is added.
const demoMastery={
  counting:100,arith_ops:100,fractions:95,decimals:90,neg_nums:88,
  divisibility:72,primes_elem:60,ratio_prop:55,
  pre_alg:80,alg1:45,precalc:30,
  eucl_geom:100,trig:82,coord_geom:70,
  informal_logic:50,logic_basic:40,
};
